// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PreferredEditorResolver is an autogenerated mock type for the PreferredEditorResolver type
type PreferredEditorResolver struct {
	mock.Mock
}

// Execute provides a mock function with given fields:
func (_m *PreferredEditorResolver) Execute() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
