// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	types "github.com/benjlevesque/task/types"
)

// TaskEditer is an autogenerated mock type for the TaskEditer type
type TaskEditer struct {
	mock.Mock
}

// EditTask provides a mock function with given fields: _a0, _a1
func (_m *TaskEditer) EditTask(_a0 int, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTask provides a mock function with given fields: _a0
func (_m *TaskEditer) GetTask(_a0 int) (types.Task, error) {
	ret := _m.Called(_a0)

	var r0 types.Task
	if rf, ok := ret.Get(0).(func(int) types.Task); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(types.Task)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
