// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TaskDeleter is an autogenerated mock type for the TaskDeleter type
type TaskDeleter struct {
	mock.Mock
}

// DeleteTask provides a mock function with given fields: _a0
func (_m *TaskDeleter) DeleteTask(_a0 int) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
