// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	db "github.com/benjlevesque/task/pkg/db"
	mock "github.com/stretchr/testify/mock"

	types "github.com/benjlevesque/task/types"
)

// TaskLister is an autogenerated mock type for the TaskLister type
type TaskLister struct {
	mock.Mock
}

// List provides a mock function with given fields: t
func (_m *TaskLister) List(t db.ListType) ([]types.Task, error) {
	ret := _m.Called(t)

	var r0 []types.Task
	if rf, ok := ret.Get(0).(func(db.ListType) []types.Task); ok {
		r0 = rf(t)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Task)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(db.ListType) error); ok {
		r1 = rf(t)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
